gcloud container --project group1-6m11 node-pools create xonotic-ui-pool \
--cluster xonotic-game-us \
--region us-central1 \
--tags=game-ui \
--machine-type e2-medium \
--image-type "COS_CONTAINERD" \
--disk-type "pd-standard" --disk-size 100 \
--service-account "group1@group1-6m11.iam.gserviceaccount.com" \
--num-nodes 1 \
--enable-autoscaling --min-nodes 1 --max-nodes 3 \
--no-enable-autoupgrade \
--enable-autorepair \
--max-surge-upgrade 1 \
--max-unavailable-upgrade 0 \
--shielded-secure-boot --shielded-integrity-monitoring \
--node-locations "us-central1-a","us-central1-b","us-central1-c" \
--node-labels=pool=xonotic-ui-pool
