gcloud beta container --project group1-6m11 clusters create xonotic-game-us \
--region us-central1 \
--cluster-version 1.20.8-gke.900 \
--tags=game-server \
--scopes=gke-default \
--machine-type e2-standard-2 \
--image-type "COS_CONTAINERD" \
--disk-type "pd-standard" --disk-size 100 \
--service-account "group1@group1-6m11.iam.gserviceaccount.com" \
--num-nodes 1 \
--logging=SYSTEM,WORKLOAD \
--monitoring=SYSTEM \
--enable-ip-alias --network "projects/group1-6m11/global/networks/demo-vpc" \
--subnetwork "projects/group1-6m11/regions/us-central1/subnetworks/subnet-us" \
--enable-autoscaling --min-nodes 1 --max-nodes 3 \
--addons HorizontalPodAutoscaling,HttpLoadBalancing,NodeLocalDNS,GcePersistentDiskCsiDriver \
--no-enable-autoupgrade \
--enable-autorepair \
--max-surge-upgrade 1 \
--max-unavailable-upgrade 0 \
--enable-shielded-nodes --shielded-secure-boot --shielded-integrity-monitoring \
--node-locations "us-central1-a","us-central1-b","us-central1-c"